title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-14
owner: ucsb-cs156-f24
repo_name: team02-f24-14
pull_requests: [{"author":{"id":"U_kgDOBfiN4g","is_bot":false,"login":"amanpdesai","name":"Aman Desai"},"headRefName":"aman-UCSBDiningCommonsMenuItem-index-page-new","number":103,"title":"UCSBDiningCommonsMenuItem Index Page","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/103"},{"author":{"id":"U_kgDOCL-YGQ","is_bot":false,"login":"rionapampati","name":""},"headRefName":"riona_indexpage","number":101,"title":" Index Page for MenuItemReview plus tests and stories #41","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/101"},{"author":{"id":"U_kgDOBfiN4g","is_bot":false,"login":"amanpdesai","name":"Aman Desai"},"headRefName":"aman-UCSBDiningCommonsMenuItem-copy-placeholders","number":97,"title":"Finished Copy Placeholders","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/97"},{"author":{"id":"U_kgDOBtnv0w","is_bot":false,"login":"Refinnej04","name":""},"headRefName":"Jennifer-HelpRequest-FormComponent","number":96,"title":"create HelpRequest Form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/96"},{"author":{"id":"U_kgDOBfiN4g","is_bot":false,"login":"amanpdesai","name":"Aman Desai"},"headRefName":"aman-UCSBDiningCommonsMenuItem-edit-page","number":94,"title":"UCSBDiningCommonsMenuItem Edit Page done","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/94"},{"author":{"id":"U_kgDOBtnv0w","is_bot":false,"login":"Refinnej04","name":""},"headRefName":"Jennifer-HelpRequest-backend","number":78,"title":"Create fixtures for HelpRequest ","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/78"}]
