
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-14
owner: ucsb-cs156-f24
repo_name: team02-f24-14
pull_requests: [{"author":{"id":"MDQ6VXNlcjY2MjE4ODE3","is_bot":false,"login":"oviyaseeniraj","name":""},"headRefName":"oviya_fixtures","number":77,"title":"Recommendation request fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/77"},{"author":{"id":"MDQ6VXNlcjY2MjE4ODE3","is_bot":false,"login":"oviyaseeniraj","name":""},"headRefName":"oviya_crud","number":76,"title":"copied crud","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/76"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"vala-Articles-edit-page","number":72,"title":"Implement EditPage for Articles plus tests/stories","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/72"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"vala-Articles-index-page","number":71,"title":"Implement IndexPage for Articles plus tests/stories","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/71"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"vala-Articles-create-page","number":70,"title":"Implement CreatePage for Articles plus tests/stories","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/70"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"vala-Articles-placeholders","number":69,"title":"Copy placeholders and tests for Articles pages, add Articles to navbar and app.js","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/69"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"vala-Articles-table-component","number":68,"title":"Create Articles Table component and tests/stories","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/68"}]
