title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-14
owner: ucsb-cs156-f24
repo_name: team02-f24-14
pull_requests: [{"author":{"id":"U_kgDOBtnv0w","is_bot":false,"login":"Refinnej04","name":""},"headRefName":"jennifer_placeholder2","number":125,"title":"Placeholder & AppNavBar tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/125"},{"author":{"id":"U_kgDOBtnv0w","is_bot":false,"login":"Refinnej04","name":""},"headRefName":"jennifer-Placeholder","number":122,"title":"Copy Placeholders for HelpRequest pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/122"},{"author":{"id":"U_kgDOBtnv0w","is_bot":false,"login":"Refinnej04","name":""},"headRefName":"jennifer_table","number":105,"title":"Table Component for HelpRequest plus tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/105"},{"author":{"id":"U_kgDOBtnv0w","is_bot":false,"login":"Refinnej04","name":""},"headRefName":"Jennifer-HelpRequest-FormComponent","number":96,"title":"create HelpRequest Form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/96"},{"author":{"id":"U_kgDOBtnv0w","is_bot":false,"login":"Refinnej04","name":""},"headRefName":"Jennifer-HelpRequest-backend","number":78,"title":"Create fixtures for HelpRequest ","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/78"}]
