
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-14
owner: ucsb-cs156-f24
repo_name: team02-f24-14
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"vala-Articles-fixtures","number":62,"title":"Create Articles Fixtures ","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/62"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"vala-Articles-backend","number":61,"title":"Create Articles CRUD backend","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/61"}]
