title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-14
owner: ucsb-cs156-f24
repo_name: team02-f24-14
pull_requests: [{"author":{"id":"U_kgDOB76BMA","is_bot":false,"login":"kev-yan","name":""},"headRefName":"kevin-UCSBOrganization-indexPage","number":114,"title":"created ucsb organization index page","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/114"},{"author":{"id":"U_kgDOB76BMA","is_bot":false,"login":"kev-yan","name":""},"headRefName":"kevin-UCSBOrganization-createPage","number":113,"title":"Created UCSB Organization create page","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/113"},{"author":{"id":"U_kgDOB76BMA","is_bot":false,"login":"kev-yan","name":""},"headRefName":"kevin-UCSBOrganization-placeholders","number":110,"title":"Created UCSB Organization placeholders","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/110"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"vala-team03-e2e","number":108,"title":"Create two end-to-end web integration test for articles (team03)","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/108"},{"author":{"id":"U_kgDOB76BMA","is_bot":false,"login":"kev-yan","name":""},"headRefName":"kevin-UCSBOrganization-table","number":107,"title":"implemented table and fixed utils file","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/107"},{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"vala-team03-integration","number":106,"title":"Create Articles' integration test (team03).","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/106"},{"author":{"id":"U_kgDOBtnv0w","is_bot":false,"login":"Refinnej04","name":""},"headRefName":"jennifer_table","number":105,"title":"Table Component for HelpRequest plus tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/105"},{"author":{"id":"U_kgDOBtnv0w","is_bot":false,"login":"Refinnej04","name":""},"headRefName":"Jennifer-HelpRequest-FormComponent","number":96,"title":"create HelpRequest Form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/96"},{"author":{"id":"U_kgDOBtnv0w","is_bot":false,"login":"Refinnej04","name":""},"headRefName":"Jennifer-HelpRequest-backend","number":78,"title":"Create fixtures for HelpRequest ","url":"https://github.com/ucsb-cs156-f24/team02-f24-14/pull/78"}]
